dataset:
  name: mouse
  dataset: mouse_E1S1
  n_clusters: 12

preprocessing:
  highly_genes: 3000
  min_cells: 100
  target_sum: 10000.0
  scale_max_value: 10.0
  gft_on_feature: 1

graph:
  gft_fraction_feature: 0.28
  radius: 1.1
  k: 20
  fusion_k: 20
  fusion_t: 15
  spatial_knn_k: 20
model:
  nhid1: 128
  nhid2: 64
  dropout: 0.1
  att_hidden: 16

training:
  epochs: 600
  lr: 0.0005
  weight_decay: 0.0001
  seed: 637602023
  alpha: 1.0
  beta: 1.0
  gamma: 1.0
  lambda_entropy: 0.1
  eval_interval: 25

